openapi: "3.0.0"
info:
  version: 1.0.0
  title: Svetit MS Project
  license:
    name: Apache-2.0
servers:
  - url: https://svetit-io/api
paths:
  /project/project/list:
    get:
      summary: List all projects
      operationId: handler-project-list-get
      tags:
        - main
      parameters:
        - $ref: "#/components/parameters/limitParam"
        - name: start
          in: query
          description: Offset position
          required: true
          schema:
            type: integer
            maximum: 999
            format: int32
        - $ref: "#/components/parameters/headerXUser"
      responses:
        '200':
          description: A paged array of projects
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Projects"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  parameters:
    limitParam:
      name: limit
      in: query
      description: How many items to return at one time (max 1000)
      required: true
      schema:
        type: integer
        maximum: 1000
        format: int32
    headerXUser:
      name: X-User
      in: header
      description: Authorized user
      required: true
      schema:
        type: string
        format: uuid
  schemas:
    Project:
      type: object
      required:
        - spaceId
        - key
        - name
        - sync
      properties:
        id:
          type: string
          format: uuid
        spaceId:
          type: string
          format: uuid
        key:
          type: string
        name:
          type: string
        description:
          type: string
        changedAt:
          type: integer
          format: int64
        sync:
          type: string
          enum:
            - projectToNode
            - nodeToProject
    Projects:
      type: array
      maxItems: 100
      items:
        $ref: "#/components/schemas/Project"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string